name: MAP

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Run actions
        run: echo Hello, world!

      - name: Run apt install
        run: |
          sudo apt-get update
          sudo apt-get install -y libgdiplus
          sudo apt-get install -y libc6-dev
          sudo apt-get install -y unzip

      - name: Run wget
        run: |
          wget https://github.com/papyrus-mc/papyruscs/releases/download/v0.5.2.2/papyruscs-dotnetcore-0.1.1.33-linux64.zip
          unzip papyruscs-dotnetcore-0.1.1.33-linux64.zip
